#!/usr/bin/env bash
set -e



message_to_send() {
  cat <<EOF
{
    "msgtype": "markdown",
    "markdown": {
        "content": "Ops!!Pipeline failed\n
         >commit id:<font color=\"comment\">$1</font>
    }
}

EOF
echo "commit id: $1"
echo "repo name: $2"
echo "branch name: $3"
echo "commit person: $4"
}

curl -H "Content-Type: application/json" -X POST -d "$(message_to_send $1 $2 $3 $4)" $5