#!/usr/bin/env bash
set -e

message_to_send() {
  SHORT_SHA=`echo $GITHUB_SHA | cut -c1-8`
  cat <<EOF
{
    "msgtype": "markdown",
    "markdown": {
        "content": "Ooops!! The pipeline failed. \n
         >commit id: <font color=\"comment\">[$SHORT_SHA](https://github.com/$GITHUB_REPOSITORY/commit/$GITHUB_SHA)</font>
         >repository: <font color=\"comment\">$GITHUB_REPOSITORY</font>
         >branch: <font color=\"comment\">$GITHUB_REF_NAME</font>
         >person: <font color=\"comment\">$GITHUB_ACTOR</font>\n
         \nYou can check it here [failed pipeline](https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID)"
    }
}
EOF
}

#curl -H "Content-Type: application/json" -X POST -d "$(message_to_send)" $(echo $webhook_url | base64 --decode)
curl -H "Content-Type: application/json" -X POST -d "$(message_to_send)" $(webhook_url)
