name: bot-reminder-test
on: [push]

permissions:
  id-token: write
  contents: read

env:
  webhook_url: ${{ secrets.WEBHOOK_URL }} | base64 --decode

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./auto/send_message ${{ github.sha }} ${{ github.repository }} ${{ github.ref_name}} ${{ github.actor}} ${{ github.run_id }} ${{ env.webhook_url }}