name: bot-reminder-test
on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./auto/send_message ${{ github.sha }} ${{ github.repository }} ${{ github.ref_name}} ${{ github.actor}} ${{ github.run_id }} "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=f297edbe-7736-4fe9-bad2-8db4047d8f6f"