name: push images to ECR

on:
  workflow_run:
    workflows: [ 'unit-test' ]
    types: [ completed ]

permissions:
  id-token: write
  contents: read

jobs:
  ECR-task:
    name: Build image and push to ecr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: 'ap-east-1'
          role-to-assume: 'arn:aws:iam::494526681395:role/ourshop-ecr-repo-role'

      - id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: 'ourshop2/test'
          IMAGE_TAG: ${{ github.run_id }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG