name: push images to docker hub

on: [push]

permissions:
  id-token: write
  contents: read

env:
  docker_name: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: run-unit-test
        id: unit-test
        run: ./auto/test
      - name: send-failure-message
        if: ${{ failure() && steps.unit-test.conclusion == 'failure' }}
        run: ./auto/send_message


  build-image-and-push-to-docker-hub:
    needs: [ unit-test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.docker_name }}
          password: ${{ env.docker_password }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: xinruichen/react_docker_learn_xr
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: send-failure-message
        if: ${{ failure() }}
              - run: ./auto/send_message ${{ github.sha }} ${{ github.repository }} ${{ github.ref_name}} ${{ github.actor}} ${{ github.run_id }} "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=f297edbe-7736-4fe9-bad2-8db4047d8f6f"
