name: push images to docker hub

on: [push]

env:
  docker_name: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: run-unit-test
        id: unit-test
        run: ./auto/test


  build-image-and-push-to-docker-hub:
    needs: [ unit-test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.docker_name }}
          password: ${{ env.docker_password }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: xinruichen/react_docker_learn_xr
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

#  send-message-to-bot:
#    runs-on: ubuntu-latest
#    env:
#      webhook_url: ${{ secrets.WEBHOOK_URL }}
#    if: ${{ always() && contains(needs.*.result, 'failure') }}
#    needs: [unit-test, build-image-and-push-to-docker-hub]
#    steps:
#      - uses: actions/checkout@v3
#      - run: ./auto/send_message

  send-message-to-bot:
    runs-on: ubuntu-latest
    env:
      webhook_url: https://webhook.site/6d8c08ef-ff8f-4be8-9a39-993795afcd93
    if: ${{ always() && contains(needs.*.result, 'failure') && contains(vars.MONITOR_BRANCHES, github.ref_name) }}
    needs: [unit-test, build-and-push]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - run: ./auto/send_message
