name: bot-reminder
on:
  workflow_run:
    workflows: ['push images to docker hub']
    types: [completed]


jobs:
  bot:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    env:
      commit: ${{ github.sha }}
      repository: ${{ github.repository }}
      branch: ${{ github.ref_name}}
      person: ${{ github.actor}}
      action_id: ${{ github.run_id }}
      webhook_url: ${{ secrets.WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v3
      - run: ./auto/send_message